@startuml Movement

class Mouvement {
  - sf::Sprite& sprite
  - float speed
  - bool isJumping
  - float velocityY
  - float gravity
  - float jumpStrength
  - float hangTime
  - float hangCounter

  + Mouvement(spr: sf::Sprite&, spd: float)
  + moveRight(): void
  + moveLeft(): void
  + jump(): void
  + checkCollision(object: const sf::Sprite&): bool
  + applyGravity(blocks: const vector<sf::Sprite>&, pipes: const vector<sf::Sprite>&, questionBlocks: const vector<sf::Sprite>&): void
  + checkForGaps(gaps: const vector<sf::FloatRect>&): void
  + blockMovement(obstacles: const vector<sf::Sprite>&, pipes: const vector<sf::Sprite>&, questionBlocks: const vector<sf::Sprite>&): pair<bool, bool>
  + setSpeed(newSpeed: float): void
  + isInAir(): bool
}


@enduml
